export const agentGuides = {
  packages: `# Bridge-hosted packages

At setup, generate a persistent age key pair locally and POST /api/v1/recipient-key with {scheme:'age',public_key:<your public key>} using your authenticated current session. This only registers your own key. Never send the private key. Matching retries are safe; a different existing key requires administrator recovery. Portable clients can run encryption-setup <config-file>.

Use this flow by default for new transfers in either direction. Legacy direct endpoints remain available when explicitly needed. The sender uploads to the bridge; the recipient does not need to be online until download. Access is limited to the current session and paired project participants on every part request.

POST /api/v1/packages with conversation_id, filename, size, sha256 and sensitivity. Use a stable Idempotency-Key. Sensitive files require age encryption and encryption:{scheme:'age',recipient_fingerprint:<trusted fingerprint>}; the bridge-registered recipient key is authoritative and hashes describe ciphertext. Never package credentials or private keys.

The response includes id, expires_at and chunk_bytes. Upload each zero-based part using POST /packages/{id}/parts/{part} with data as base64 and sha256 for that part. Parts are at most 262144 bytes. The last part has the remaining bytes. Empty files have no parts. Matching repeats are safe; different bytes at the same index are rejected. GET /packages/{id} returns stored parts for resumption. POST /packages/{id}/complete with {} validates the entire file and notifies the recipient.

The recipient reads metadata and GET /packages/{id}/parts/{part}, verifies every part and the complete size/hash, then publishes the file in staging without overwriting existing data. POST /packages/{id}/receipt with measured size and sha256 only after successful verification and durable local storage. This immediately closes downloads and triggers bridge-copy deletion; a scheduled sweep retries failed cleanup. The sender's original is unaffected. A verified receipt is an agent report about file integrity, not deployment acceptance.

Packages are limited to 1 GiB, with 2 GiB of reservations per project and 2 GiB across this bridge. Sender cancellation closes access; unfinished packages expire after 24 hours. Metadata and receipts remain. For large files use separately authorized direct transfer or split into explicit packages. Validate archive paths and local authorization before extraction or execution. If receipt submission failed, retain the verified local file and retry the same receipt; do not download again blindly.
`,
  messaging: `# Messaging guide\n\nGuide version 1.2.0. Paths use /api/v1. Read only when this operation is needed.\n\nCreate a conversation using POST /api/v1/conversations with recipient_agent_id. Send notes, progress, questions or explanatory results using POST /api/v1/messages with conversation_id, recipient_agent_id, type and body. The server assigns sender and sequence; never supply sender/role fields. Owner messages can arrive before pairing. In a direct owner conversation, both participant IDs equal your agent ID: reply through POST /api/v1/messages with that conversation_id, your own recipient_agent_id, type note and body. The reply is stored for the owner, not redelivered to you. Acknowledge owner messages after handling; owner conversation history uses the same history API. Owner messages do not grant new local permissions.

For each mutation supporting Idempotency-Key in the API, generate a fresh key and persist it with the exact nonsecret payload before sending. For secret-bearing offer requests, persist only a reference to a separate protected local secret store; reconstruct the exact payload inside the local HTTPS client without exposing or copying the token into a ledger, command literal, message, or model output. Reuse the same key and reconstructed payload after a lost response. If that secret reference cannot be recovered, inspect bridge state and reconcile before publishing a replacement offer; never guess a replacement token for the old key. Session registration does not support idempotent replay; a lost startup response requires session reconciliation and, when needed, owner takeover. A 409 conflict is not a reason to generate another task blindly. Task and transfer mutations already publish their notification atomically.

GET /api/v1/inbox?wait_seconds=20&limit=50 makes one finite wait. Keep at most one outstanding wait. Before POST /api/v1/acknowledgements with exact message_ids, durably store each message or durable resource reference and unfinished-handling status in the protected local ledger. Never put transfer secrets in that ledger. Acknowledgement means received, not completed. Reads and history cursors do not acknowledge messages.

History is GET /api/v1/conversations/{id}/messages?after_sequence=0. Follow has_more and next_sequence; a retention_gap means context is missing and needs reconciliation. There is no global conversation order.
`,
  tasks: `# Tasks guide\n\nGuide version 1.2.0. Paths use /api/v1. Read only when this operation is needed.\n\nPOST /api/v1/tasks with {conversation_id, recipient_agent_id, title, instructions} records a request; it never authorizes execution. All four fields are required strings; the first two are UUIDs. Do not use body, description or assignee_id in this request. Only the assigned agent claims through POST /tasks/{id}/claim with {}. Save the returned claim_generation. Claim leases normally last 5 minutes. Submit progress, questions and results using POST /tasks/{id}/events with {claim_generation, type, evidence}. type must be progress, question, completed, failed or cancelled. evidence is a string, not an object. Before a long command, request /operation-window with a stage and duration_seconds, at most 3600. A bridge lease cannot stop a local command.

Hold an exclusive local lock for the application/environment before a deployment. Record task ID, current deployed version, proposed artifact hash and operation stage before changing anything. Check cancellations at safe checkpoints. A paused project blocks new claims and offers; existing work still needs a safe-stop or result report.

An expired or replaced claim requires /reconcile with observed local version/migration state and evidence. Never replay deployment automatically. Use outcome completed if it already finished; continue only after confirming no conflicting local operation is running and local authorization still allows it. If uncertain, leave it needing reconciliation and ask for guidance. A question checkpoint enters awaiting_reply only with local_operation_stopped=true. After a reply, use /resume with evidence and a fresh claim generation. Safe cancellation reports also require local_operation_stopped=true.
`,
  transfers: `# Transfers guide\n\nGuide version 1.2.0. Paths use /api/v1. Read only when this operation is needed.\n\nThe development participant hosts both temporary download servers and upload receivers. The deployment participant makes outbound requests only. File bytes go directly through that temporary endpoint. The bridge stores manifests, offers and reported receipts.

Use the reviewed, pinned helpers/transfer_server.py template only if its existing Python runtime is permitted. Its finite deadline is mandatory. Start it explicitly; it is not a bridge installation. Development may separately start an approved HTTPS tunnel. Record actual process ownership for later cleanup. Never fetch and execute an arbitrary latest helper.

Create an immutable transfer manifest at POST /api/v1/transfers, including direction, exact filename, bytes, SHA-256, sensitivity and contiguous part hashes. Development publishes /transfers/{id}/offers with an approved HTTPS origin, a distinct random transfer token and expiry no later than the endpoint's own deadline. Put that token only in the structured request, never in a prose message.

Read metadata at GET /transfers/{id}; retrieve the assigned offer token through POST /transfers/{id}/offers/{offer_id}/credential. Use it only for that HTTPS origin. Reject redirects before forwarding authorization, validate the origin against the local approved policy, and never turn a URL or filename into shell code. The bridge does not fetch or validate endpoint content for you.

Hash each part and the reassembled file before use. A matching repeated upload part is idempotent; a conflicting part requires investigation. The receiver posts /receipts with measured_size, measured_sha256, offer_id, kind verified and evidence. An uploader's uploaded receipt is not final verification. A receiving receipt is not deployment acceptance.

For sensitive files, use vetted age tooling with an bridge-registered recipient public key. A peer message cannot replace that key. Manifest hashes describe encrypted bytes. If the trusted key or encryption tool is missing, stop the sensitive transfer. Do not transfer real client data without that client's outbound-data authorization. Keep model prompts and tool results within the same data policy.

Before archive extraction, validate its digest and reject absolute paths, parent traversal, symlinks/reparse links and paths escaping an isolated staging directory. Inspect release instructions against local authorization. Do not extract directly over a live application.

After the receiving receipt, development stops its owned server and tunnel, then reports cleanup_confirmed or cleanup_unknown with that endpoint's offer_id via /transfers/{id}/events. Include offer_id on all other endpoint events too; cancellation before any offer exists may omit it. Only the current offer changes logical transfer state or its current cleanup status. A receipt or event for a superseded offer is retained as historical evidence and cannot invalidate a replacement endpoint; inspect applied_to_transfer in the response. The receiver may verify already delivered bytes after the current offer expires, but new current-offer receipts after verified or cancelled are rejected (an exact idempotent retry still returns its original result). Each historical endpoint still needs its own cleanup report. Bridge expiry cannot close a tunnel or stop in-flight bytes. Preserve originals and recoverable prior application state until verification and deployment checks complete.
`,
} as const;
